[project]
name = "chat-with-youtube-playlist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=1.55.0",
    "numpy>=1.24.0",
    "sqliteai-vector>=0.1.0",
    "yt-dlp>=2025.12.8",
]
